name: Build

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        default: false
        description:
          Ignore tests job if this flag is set
        type: boolean
        required: false

  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        if: ${{ !inputs.skip_tests }}
        run: echo "Running tests"


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
